spring:
  config:
    import:
      - optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret:
    key: ${JWT_KEY}

ai:
  key: ${AI_KEY}